apk: Support replacing existing debuggable attribute
frida/frida-tools pull request #166
Opened 2024-10-08 18:27 UTC by tchebb

If a package explicitly specifies debuggable="false", adding a new entry setting it to "true" has no effect. To properly patch such APKs, we need to replace the entry.

This contribution is on behalf of my company.

2024-10-09 04:30 UTC, s1341 commented
Has this been tested?

2024-10-18 16:32 UTC, tchebb commented
Yes. I've tested it on both the Facebook app (`com.facebook.katana.456014858.apk` as of today, downloadable from [here](https://www.facebook.com/android_upgrade)) and the Magisk app ([`Magisk-v28.0.apk`](https://github.com/topjohnwu/Magisk/releases/download/v28.0/Magisk-v28.0.apk)). frida-apk works on Magisk both before and after this PR, while it only works on Facebook after this PR.

Here are how the apps' manifests look on the unmodified APKs:
```
$ aapt d xmltree com.facebook.katana.456014858.apk AndroidManifest.xml | grep android:debuggable
      A: android:debuggable(0x0101000f)=(type 0x12)0x0
$ aapt d xmltree Magisk-v28.0.apk AndroidManifest.xml | grep android:debuggable
<no output>
```

Here's how they look after frida-apk, without this PR (note the duplicate entry on the Facebook APK):
```
$ aapt d xmltree com.facebook.katana.456014858.d-current.apk AndroidManifest.xml | grep android:debuggable
      A: android:debuggable(0x0101000f)=(type 0x12)0x0
      A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
$ aapt d xmltree Magisk-v28.0.d-current.apk AndroidManifest.xml | grep android:debuggable
      A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
```

And here's how they look after frida-apk, with this PR:
```
$ aapt d xmltree com.facebook.katana.456014858.d-new.apk AndroidManifest.xml | grep android:debuggable
      A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
$ aapt d xmltree Magisk-v28.0.d-new.apk AndroidManifest.xml | grep android:debuggable
      A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
```

On my Pixel 5 running Android 14, `xmltree com.facebook.katana.456014858.d-new.apk` shows up as debuggable when installed, while `com.facebook.katana.456014858.d-current.apk` doesn't.

2024-10-18 22:09 UTC, oleavr requested changes
Thanks for doing this! :raised_hands:

2024-10-18 22:09 UTC, oleavr commented on frida_tools/apk.py
> +                # If there's already a debugging resource, replace it.
```suggestion
```

Code already makes this clear.

2024-10-18 22:09 UTC, oleavr commented on frida_tools/apk.py
> +            attr_offset = 0x24 + struct.calcsize(self.ATTRIBUTE_FORMAT) * insert_pos
```suggestion
            attr_offset = 0x24 + insert_pos * struct.calcsize(self.ATTRIBUTE_FORMAT)
```

Nit: Existing code has the quantity first, size second.

2024-10-18 22:10 UTC, merged