Add help command that displays list of commands
frida/frida-tools pull request #77
Opened 2022-01-27 09:38 UTC by yotamN

Together with some refactor to make it possible, I've added an help message (and an unload message that was declared but not implemented).

I've developed it over my other patch of auto java perform because it touched the same code area and I wanted to minimize merge conflicts later, hope it's okay.

2022-01-31 22:15 UTC, oleavr requested changes
Wow, nice. Thanks!

2022-01-31 22:15 UTC, oleavr commented on frida_tools/_magics.py
> +
Shouldn't there be two blank lines here according to PEP-8? (I might me misremembering but at least this is the convention I've used — so hope I didn't get it wrong 😅)

2022-01-31 22:15 UTC, oleavr commented on frida_tools/_magics.py
> +        return "reload (i.e. rerun) the script that was given as an argument to the repl"
```suggestion
        return "reload (i.e. rerun) the script that was given as an argument to the REPL"
```

2022-01-31 22:15 UTC, oleavr commented on frida_tools/_magics.py
> +        return "sesume execution of the attached process"
```suggestion
        return "resume execution of the spawned process"
```

2022-01-31 22:15 UTC, oleavr commented on frida_tools/_magics.py
> +        return "receive on/off as first and only argument, when switched on will wrap any repl code with Java.PerformNow"
```suggestion
        return "receive on/off as first and only argument, when switched on will wrap any REPL code with Java.performNow()"
```

2022-01-31 22:15 UTC, oleavr commented on frida_tools/_magics.py
> +        return "print a list of available repl commands"
```suggestion
        return "print a list of available REPL commands"
```

2022-01-31 22:15 UTC, oleavr commented on frida_tools/_magics.py
> +import abc
Perhaps we should name this file `_repl_magic` or something? (Plural sounds a bit strange so perhaps singular is better?)

2022-02-01 05:40 UTC, yotamN commented
Fixed everything and rebased

2022-02-01 10:25 UTC, oleavr commented
Thanks! Conflicts ⚔️

2022-02-01 17:46 UTC, yotamN commented
Fixed

2022-02-05 22:26 UTC, oleavr commented
Conflicts ⚔️

2022-02-06 05:36 UTC, yotamN commented
rebased again

2022-02-06 09:18 UTC, merged

2022-02-15 09:04 UTC, starplanet commented
There is a bug that _repl_magic.py is not listed in meson.build file. It will cause frida to fail to compile